apiVersion: apps/v1
kind: Deployment
metadata:
  name: secom-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: secom-api
  template:
    metadata:
      labels:
        app: secom-api
    spec:
      containers:
        - name: secom-api
          image: khaoulaboughattas/secom-api:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8000
