apiVersion: v1
kind: Service
metadata:
  name: secom-api-service
spec:
  selector:
    app: secom-api
  type: NodePort
  ports:
    - port: 8000
      targetPort: 8000
      nodePort: 30007
